pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('List Files') {
            steps {
                echo 'Listing files from repo'
                bat 'dir' // Changed from 'ls -la'
            }
        }
        stage('Show HTML Preview Info') {
            steps {
                echo 'HTML Preview Info stage'
            }
        }
        stage('Done!') {
            steps {
                echo 'Pipeline completed successfully!'
            }
        }
    }
}
