pipeline {
    agent any

    stages {
        stage('List Files') {
            steps {
                echo 'Listing files from repo'
                bat 'ls -la'
            }
        }

        stage('Show HTML Preview Info') {
            steps {
                echo 'inside of html file'
                bat 'head -n 10 index.html'
            }
        }

        stage('Done!') {
            steps {
                echo 'Pipeline done'
            }
        }
    }
}
